### ISSUE TITLE
Can't build on Ubuntu 18.10

### ISSUE THREAD

**Issue by NatoBoram** [Zygo/bees#88]
I have followed the instructions [here](https://github.com/Zygo/bees/blob/master/docs/install.md#ubuntu-1604---1704) for Ubuntu 17.04 and couldn't build it on Ubuntu 18.10.

```log
$ sudo apt -y install build-essential btrfs-tools uuid-dev markdown && make
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'btrfs-progs' instead of 'btrfs-tools'
btrfs-progs is already the newest version (4.16.1-2ubuntu1).
build-essential is already the newest version (12.5ubuntu2).
uuid-dev is already the newest version (2.32-0.1ubuntu2).
markdown is already the newest version (1.0.1-10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

make PREFIX=/usr LIBEXEC_PREFIX=/usr/lib/bees ETC_PREFIX=/etc -C lib
make[1]: Entering directory '/home/nato/Documents/GitHub/bees/lib'
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/extentwalker.dep -MT extentwalker.o extentwalker.cc
In file included from ../include/crucible/fs.h:9,
                 from extentwalker.cc:5:
../include/crucible/btrfs.h:17:10: fatal error: btrfs/ioctl.h: No such file or directory
 #include <btrfs/ioctl.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
Makefile:44: depends.mk: No such file or directory
make[1]: *** [Makefile:34: .depends/extentwalker.dep] Error 1
make[1]: Leaving directory '/home/nato/Documents/GitHub/bees/lib'
make: *** [Makefile:34: lib] Error 2
```

```yaml
OS: Ubuntu 18.10 x86_64 
Kernel: 4.18.0-11-generic 
Uptime: 12 hours, 8 mins 
Packages: 2123 (dpkg), 42 (snap) 
Shell: bash 4.4.19 
Resolution: 1920x1080 
DE: GNOME 3.30.1 
WM: GNOME Shell 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-3570K (4) @ 3.800GHz 
GPU: NVIDIA GeForce GTX 660 Ti 
Memory: 4247MiB / 7921MiB 
```

**Comment by kakra** [comment]
You are probably missing the kernel or btrfs headers, please install those. The package should be named `linux-headers` but I'm not Ubuntu expert/user.

**Comment by NatoBoram** [comment]
I searched for `linux-headers`, but this is all I found. There's nothing about btrfs in there.

```bash
nato@NatoHelionUbuntu:~$ apt install linux-headers-
linux-headers-4.15.0-1021-oem       linux-headers-4.18.0-11
linux-headers-4.15.0-1024-oem       linux-headers-4.18.0-11-generic
linux-headers-4.15.0-1026-oem       linux-headers-4.18.0-11-lowlatency
linux-headers-4.18.0-10             linux-headers-aws
linux-headers-4.18.0-1002-aws       linux-headers-azure
linux-headers-4.18.0-1002-gcp       linux-headers-azure-edge
linux-headers-4.18.0-1003-azure     linux-headers-gcp
linux-headers-4.18.0-1003-gcp       linux-headers-generic
linux-headers-4.18.0-1003-kvm       linux-headers-gke
linux-headers-4.18.0-1004-aws       linux-headers-kvm
linux-headers-4.18.0-1004-kvm       linux-headers-lowlatency
linux-headers-4.18.0-10-generic     linux-headers-oem
linux-headers-4.18.0-10-lowlatency  linux-headers-virtual
```

Those are the ones I have installed : 

```bash
nato@NatoHelionUbuntu:~$ sudo apt purge linux-headers-
linux-headers-4.18.0-10          linux-headers-4.18.0-11-generic
linux-headers-4.18.0-10-generic  linux-headers-generic
linux-headers-4.18.0-11          
```

Do you have an exact package name I can install to test it out?

**Comment by kakra** [comment]
Could you run `apt-cache search btrfs` and `apt-cache search headers` and see if there are `...-dev` or `...-headers` packages obviously missing in your installation? The message "Note, selecting 'btrfs-progs' instead of 'btrfs-tools'" looks suspicious. Maybe Ubuntu split-out headers into a separate package and our instructions have to be adjusted. Maybe the headers are in "btrfs-progs-dev" now or something.

Looking at https://packages.ubuntu.com/source/cosmic/btrfs-progs suggests it's called `libbtrfs-dev` now.

**Comment by NatoBoram** [comment]
It seems like it was indeed `libbtrfs-dev`!

So, the build process looked like that : 

```log
make PREFIX=/usr LIBEXEC_PREFIX=/usr/lib/bees ETC_PREFIX=/etc -C lib
make[1]: Entering directory '/home/nato/Documents/GitHub/bees/lib'
sed configure.h.in >configure.h -e's#@PREFIX@#/usr#' -e's#@ETC_PREFIX@#/etc#' -e's#@LIBEXEC_PREFIX@#/usr/lib/bees#'
mkdir -p .depends
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/chatter.dep -MT chatter.o chatter.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/cleanup.dep -MT cleanup.o cleanup.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/crc64.dep -MT crc64.o crc64.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/error.dep -MT error.o error.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/extentwalker.dep -MT extentwalker.o extentwalker.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/fd.dep -MT fd.o fd.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/fs.dep -MT fs.o fs.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/ntoa.dep -MT ntoa.o ntoa.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/path.dep -MT path.o path.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/process.dep -MT process.o process.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/string.dep -MT string.o string.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/task.dep -MT task.o task.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/time.dep -MT time.o time.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/uuid.dep -MT uuid.o uuid.cc
cat .depends/chatter.dep .depends/cleanup.dep .depends/crc64.dep .depends/error.dep .depends/extentwalker.dep .depends/fd.dep .depends/fs.dep .depends/ntoa.dep .depends/path.dep .depends/process.dep .depends/string.dep .depends/task.dep .depends/time.dep .depends/uuid.dep > depends.mk.new
mv -f depends.mk.new depends.mk
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -fPIC -o chatter.o -c chatter.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -fPIC -o cleanup.o -c cleanup.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -fPIC -o crc64.o -c crc64.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -fPIC -o error.o -c error.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -fPIC -o extentwalker.o -c extentwalker.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -fPIC -o fd.o -c fd.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -fPIC -o fs.o -c fs.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -fPIC -o ntoa.o -c ntoa.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -fPIC -o path.o -c path.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -fPIC -o process.o -c process.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -fPIC -o string.o -c string.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -fPIC -o task.o -c task.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -fPIC -o time.o -c time.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -fPIC -o uuid.o -c uuid.cc
echo "namespace crucible { const char *VERSION = \"v0.6-35-ge74122b\"; }" > .version.cc.new
mv -f .version.cc.new .version.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -fPIC -o .version.o -c .version.cc
g++  -fPIC -shared -Wl,-soname,libcrucible.so -o libcrucible.so chatter.o cleanup.o crc64.o error.o extentwalker.o fd.o fs.o ntoa.o path.o process.o string.o task.o time.o uuid.o .version.o -luuid
make[1]: Leaving directory '/home/nato/Documents/GitHub/bees/lib'
make PREFIX=/usr LIBEXEC_PREFIX=/usr/lib/bees ETC_PREFIX=/etc BEES_VERSION="v0.6-35-ge74122b" -C src
make[1]: Entering directory '/home/nato/Documents/GitHub/bees/src'
mkdir -p .depends
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/bees.dep -MT bees.o bees.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/bees-context.dep -MT bees-context.o bees-context.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/bees-hash.dep -MT bees-hash.o bees-hash.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/bees-resolve.dep -MT bees-resolve.o bees-resolve.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/bees-roots.dep -MT bees-roots.o bees-roots.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/bees-thread.dep -MT bees-thread.o bees-thread.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/bees-types.dep -MT bees-types.o bees-types.cc
cat .depends/bees.dep .depends/bees-context.dep .depends/bees-hash.dep .depends/bees-resolve.dep .depends/bees-roots.dep .depends/bees-thread.dep .depends/bees-types.dep > depends.mk.new
mv -f depends.mk.new depends.mk
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -o bees.o -c bees.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -o bees-context.o -c bees-context.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -o bees-hash.o -c bees-hash.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -o bees-resolve.o -c bees-resolve.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -o bees-roots.o -c bees-roots.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -o bees-thread.o -c bees-thread.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -o bees-types.o -c bees-types.cc
echo "const char *BEES_VERSION = \"v0.6-35-ge74122b\";" > bees-version.new.c
mv -f bees-version.new.c bees-version.c
cc -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c99  -o bees-version.o -c bees-version.c
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -L../lib  -o ../bin/bees bees.o bees-context.o bees-hash.o bees-resolve.o bees-roots.o bees-thread.o bees-types.o bees-version.o -lcrucible -lpthread
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -o fiemap.o -c fiemap.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -L../lib  -o ../bin/fiemap fiemap.o -lcrucible -lpthread
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -o fiewalk.o -c fiewalk.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -L../lib  -o ../bin/fiewalk fiewalk.o -lcrucible -lpthread
make[1]: Leaving directory '/home/nato/Documents/GitHub/bees/src'
sed scripts/beesd.in >scripts/beesd -e's#@PREFIX@#/usr#' -e's#@ETC_PREFIX@#/etc#' -e's#@LIBEXEC_PREFIX@#/usr/lib/bees#'
sed scripts/beesd@.service.in >scripts/beesd@.service -e's#@PREFIX@#/usr#' -e's#@ETC_PREFIX@#/etc#' -e's#@LIBEXEC_PREFIX@#/usr/lib/bees#'
make PREFIX=/usr LIBEXEC_PREFIX=/usr/lib/bees ETC_PREFIX=/etc -C docs
make[1]: Entering directory '/home/nato/Documents/GitHub/bees/docs'
P: how-it-works.md | sed -e 's/\.md/\.html/g' > how-it-works.html.new
/bin/sh: 1: P:: not found
mv -f how-it-works.html.new how-it-works.html
P: running.md | sed -e 's/\.md/\.html/g' > running.html.new
/bin/sh: 1: P:: not found
mv -f running.html.new running.html
P: btrfs-other.md | sed -e 's/\.md/\.html/g' > btrfs-other.html.new
/bin/sh: 1: P:: not found
mv -f btrfs-other.html.new btrfs-other.html
P: install.md | sed -e 's/\.md/\.html/g' > install.html.new
/bin/sh: 1: P:: not found
mv -f install.html.new install.html
P: config.md | sed -e 's/\.md/\.html/g' > config.html.new
/bin/sh: 1: P:: not found
mv -f config.html.new config.html
P: missing.md | sed -e 's/\.md/\.html/g' > missing.html.new
/bin/sh: 1: P:: not found
mv -f missing.html.new missing.html
P: gotchas.md | sed -e 's/\.md/\.html/g' > gotchas.html.new
/bin/sh: 1: P:: not found
mv -f gotchas.html.new gotchas.html
P: index.md | sed -e 's/\.md/\.html/g' > index.html.new
/bin/sh: 1: P:: not found
mv -f index.html.new index.html
P: options.md | sed -e 's/\.md/\.html/g' > options.html.new
/bin/sh: 1: P:: not found
mv -f options.html.new options.html
P: wrong.md | sed -e 's/\.md/\.html/g' > wrong.html.new
/bin/sh: 1: P:: not found
mv -f wrong.html.new wrong.html
P: btrfs-kernel.md | sed -e 's/\.md/\.html/g' > btrfs-kernel.html.new
/bin/sh: 1: P:: not found
mv -f btrfs-kernel.html.new btrfs-kernel.html
P: ../README.md | sed -e 's/\.md/\.html/g' > ../README.html.new
/bin/sh: 1: P:: not found
mv -f ../README.html.new ../README.html
make[1]: Leaving directory '/home/nato/Documents/GitHub/bees/docs'
make PREFIX=/usr LIBEXEC_PREFIX=/usr/lib/bees ETC_PREFIX=/etc -C test
make[1]: Entering directory '/home/nato/Documents/GitHub/bees/test'
mkdir -p .depends
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/chatter.dep -MT chatter.o chatter.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/crc64.dep -MT crc64.o crc64.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/fd.dep -MT fd.o fd.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/limits.dep -MT limits.o limits.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/path.dep -MT path.o path.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/process.dep -MT process.o process.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/progress.dep -MT progress.o progress.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/task.dep -MT task.o task.cc
cat .depends/chatter.dep .depends/crc64.dep .depends/fd.dep .depends/limits.dep .depends/path.dep .depends/process.dep .depends/progress.dep .depends/task.dep > depends.mk.new
mv -f depends.mk.new depends.mk
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -o chatter.o -c chatter.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -L../lib -Wl,-rpath=/home/nato/Documents/GitHub/bees/lib  -o chatter chatter.o -lcrucible -lpthread
./chatter >chatter.txt 2>&1 || (RC=$?; cat chatter.txt; exit $RC)
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -o crc64.o -c crc64.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -L../lib -Wl,-rpath=/home/nato/Documents/GitHub/bees/lib  -o crc64 crc64.o -lcrucible -lpthread
./crc64 >crc64.txt 2>&1 || (RC=$?; cat crc64.txt; exit $RC)
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -o fd.o -c fd.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -L../lib -Wl,-rpath=/home/nato/Documents/GitHub/bees/lib  -o fd fd.o -lcrucible -lpthread
./fd >fd.txt 2>&1 || (RC=$?; cat fd.txt; exit $RC)
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -o limits.o -c limits.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -L../lib -Wl,-rpath=/home/nato/Documents/GitHub/bees/lib  -o limits limits.o -lcrucible -lpthread
./limits >limits.txt 2>&1 || (RC=$?; cat limits.txt; exit $RC)
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -o path.o -c path.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -L../lib -Wl,-rpath=/home/nato/Documents/GitHub/bees/lib  -o path path.o -lcrucible -lpthread
./path >path.txt 2>&1 || (RC=$?; cat path.txt; exit $RC)
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -o process.o -c process.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -L../lib -Wl,-rpath=/home/nato/Documents/GitHub/bees/lib  -o process process.o -lcrucible -lpthread
./process >process.txt 2>&1 || (RC=$?; cat process.txt; exit $RC)
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -o progress.o -c progress.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -L../lib -Wl,-rpath=/home/nato/Documents/GitHub/bees/lib  -o progress progress.o -lcrucible -lpthread
./progress >progress.txt 2>&1 || (RC=$?; cat progress.txt; exit $RC)
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -o task.o -c task.cc
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -L../lib -Wl,-rpath=/home/nato/Documents/GitHub/bees/lib  -o task task.o -lcrucible -lpthread
./task >task.txt 2>&1 || (RC=$?; cat task.txt; exit $RC)
make[1]: Leaving directory '/home/nato/Documents/GitHub/bees/test'
```

And there's files in `/bin/`!

```bash
nato@NatoHelionUbuntu:~/Documents/GitHub/bees$ ls bin/
bees  fiemap  fiewalk
```

However, when I try to launch `bees`, it gives me an error.

```bash
nato@NatoHelionUbuntu:~/Documents/GitHub/bees$ ./bin/bees 
./bin/bees: error while loading shared libraries: libcrucible.so: cannot open shared object file: No such file or directory
```

I tried to search for `libcrucible`, but there's no result. Is something still missing?

```bash
nato@NatoHelionUbuntu:~/Documents/GitHub/bees$ apt search libcrucible
Sorting... Done
Full Text Search... Done
```

**Comment by kakra** [comment]
It's not meant to be used directly that way, you should install it first. Otherwise it won't find `libcrucible.so`.

But you could supply it the correct path:
```bash
# LD_LIBRARY_PATH=$(pwd)/lib bin/bees
```

**Comment by Zygo** [comment]
So it's something like...

`apt -y install build-essential btrfs-progs libbtrfs-dev uuid-dev markdown && make`

?

**Comment by kakra** [comment]
@Zygo I think yes, that did it.

Could we do something about the out-of-box experience when self-building without install? Maybe link statically and create and extra make verb for building a dynamically linked exe?

**Comment by Zygo** [comment]
I don't think libcrucible needs to be dynamic for bees any more.  Once in the distant past it needed to be dynamic to force C++ to construct things properly, but I think all that code is (and all the busted C++ runtimes are) gone now.

For my own builds I just do `make install DESTDIR=...` and it just works.  We could put that in the docs.

**Comment by Donwulff** [comment]
I'll second this general libcrucible issue. I was trying to figure out what was going on & debugging for days when bees suddenly started crashing due to double free error at the start, and I could find nothing wrong with the code. Just the other day by chance I saw this unrelated bug report, and realized I'd been using old version of libcrucible by accident, and who does the memory freeing had apparently changed... At the very least the dynamic library needs to be versioned so that when the API changes things don't break horribly in mysterious ways, but if it's possible to link it static for same effort, that would be perfect.

**Comment by kakra** [comment]
The point is, if you've installed libcrucible.so once before into the system, bees compiled from source will use this (possibly outdated) lib. You need to point `LD_LIBRARY_PATH` to the path of the current lib to run bees from the source code directory. This is no quirk of bees, it applies to all source-compiled software which builds dynamic libs.

**Comment by Donwulff** [comment]
When the library API changes or software depends on specific version, library versioning is used. Or when the library is something as intrinsically related as crucible is to bees, they tend to directly load it from relative path. ("make install" uses "lib", although the hierarchy is different from build dir)

More to the point, I'm sure everybody in this issue thread is aware of why it happens and how to work around it, that's explicitly the topic, it's just not immediately obvious that is an issue especially since as the documentation like docs/wrong or docs/gotchas don't make mention of it. The off-hand mention in docs/install is easy to miss. But really, I'm just seconding your and Zygo's suggestion to link it statically, which would avoid all of this, if possible. If not, the troubleshooting/development documentation could  be amended to stress you can't run it with wrong version in the library path and/or library versioned.

**Comment by Zygo** [comment]
Commit 7933ccb660de3f4b5cd8d2ac2af00d4d4e6acdf3 makes crucible a static library (note: you _really_ need to run `make clean` after a `git pull` for that change).

Does 6cf16c4849a878d78c1f6192de22d8cd46904970 suffice for documentation?

Do we still need packaging updates?

**Comment by kakra** [comment]
Let me cross-check this before closing it...

**Comment by Zygo** [comment]
Ping?

**Comment by Donwulff** [comment]
The original issue NatoBoram had was libbtrfs-dev not being installed, but the bug-report had kind of feature creep. And I'm running Ubuntu 18.04.02 LTS, but I can confirm the changes work on that, as well as Gentoo.

**Comment by Zygo** [comment]
> I'm running Ubuntu 18.04.02 LTS, but I can confirm the changes work on that

Good enough.  Closing.

**Comment by kakra** [comment]
> Let me cross-check this before closing it...

BTW: Sorry for not following up but I didn't observe any problems with the Gentoo package.
