### ISSUE TITLE
Compiling problem

### ISSUE THREAD

**Issue by Nefelim4ag** [Zygo/bees#1]
Hi Zygo, i've try package your bees for AUR, and get the following compiling errors:
```
bees git:(master) make   
make -C lib
make[1]: Entering directory '/home/nefelim4ag/Insync/Documents/Dump/Coding/bees/lib'
g++ -Wall -Wextra -Werror -O3 -I../include -ggdb -fpic -std=c++11 -Wold-style-cast -o chatter.o -c chatter.cc
In file included from chatter.cc:1:0:
../include/crucible/chatter.h: In member function ‘crucible::Chatter& crucible::ChatterTraits<std::basic_ostream<char>&>::operator()(crucible::Chatter&, std::ostream&)’:
../include/crucible/chatter.h:94:15: error: no match for ‘operator<<’ (operand types are ‘std::ostream {aka std::basic_ostream<char>}’ and ‘std::ostream {aka std::basic_ostream<char>}’)
    c.get_os() << arg;
    ~~~~~~~~~~~^~~~~~
../include/crucible/chatter.h:94:15: note: candidate: operator<<(int, int) <built-in>
../include/crucible/chatter.h:94:15: note:   no known conversion for argument 2 from ‘std::ostream {aka std::basic_ostream<char>}’ to ‘int’
In file included from /usr/include/c++/6.2.1/iostream:39:0,
                 from ../include/crucible/chatter.h:5,
                 from chatter.cc:1:
/usr/include/c++/6.2.1/ostream:108:7: note: candidate: std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(std::basic_ostream<_CharT, _Traits>::__ostream_type& (*)(std::basic_ostream<_CharT, _Traits>::__ostream_type&)) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]
       operator<<(__ostream_type& (*__pf)(__ostream_type&))
       ^~~~~~~~
/usr/include/c++/6.2.1/ostream:108:7: note:   no known conversion for argument 1 from ‘std::ostream {aka std::basic_ostream<char>}’ to ‘std::basic_ostream<char>::__ostream_type& (*)(std::basic_ostream<char>::__ostream_type&) {aka std::basic_ostream<char>& (*)(std::basic_ostream<char>&)}’
/usr/include/c++/6.2.1/ostream:117:7: note: candidate: std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(std::basic_ostream<_CharT, _Traits>::__ios_type& (*)(std::basic_ostream<_CharT, _Traits>::__ios_type&)) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>; std::basic_ostream<_CharT, _Traits>::__ios_type = std::basic_ios<char>]
       operator<<(__ios_type& (*__pf)(__ios_type&))
       ^~~~~~~~
/usr/include/c++/6.2.1/ostream:117:7: note:   no known conversion for argument 1 from ‘std::ostream {aka std::basic_ostream<char>}’ to ‘std::basic_ostream<char>::__ios_type& (*)(std::basic_ostream<char>::__ios_type&) {aka std::basic_ios<char>& (*)(std::basic_ios<char>&)}’
/usr/include/c++/6.2.1/ostream:127:7: note: candidate: std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(std::ios_base& (*)(std::ios_base&)) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]
       operator<<(ios_base& (*__pf) (ios_base&))
       ^~~~~~~~
/usr/include/c++/6.2.1/ostream:127:7: note:   no known conversion for argument 1 from ‘std::ostream {aka std::basic_ostream<char>}’ to ‘std::ios_base& (*)(std::ios_base&)’
/usr/include/c++/6.2.1/ostream:166:7: note: candidate: std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(long int) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]
       operator<<(long __n)
       ^~~~~~~~
/usr/include/c++/6.2.1/ostream:166:7: note:   no known conversion for argument 1 from ‘std::ostream {aka std::basic_ostream<char>}’ to ‘long int’
/usr/include/c++/6.2.1/ostream:170:7: note: candidate: std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(long unsigned int) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]
       operator<<(unsigned long __n)
       ^~~~~~~~
/usr/include/c++/6.2.1/ostream:170:7: note:   no known conversion for argument 1 from ‘std::ostream {aka std::basic_ostream<char>}’ to ‘long unsigned int’
/usr/include/c++/6.2.1/ostream:174:7: note: candidate: std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(bool) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]
       operator<<(bool __n)
       ^~~~~~~~
/usr/include/c++/6.2.1/ostream:174:7: note:   no known conversion for argument 1 from ‘std::ostream {aka std::basic_ostream<char>}’ to ‘bool’
In file included from /usr/include/c++/6.2.1/ostream:638:0,
                 from /usr/include/c++/6.2.1/iostream:39,
                 from ../include/crucible/chatter.h:5,
                 from chatter.cc:1:
/usr/include/c++/6.2.1/bits/ostream.tcc:91:5: note: candidate: std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(short int) [with _CharT = char; _Traits = std::char_traits<char>]
     basic_ostream<_CharT, _Traits>::
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/6.2.1/bits/ostream.tcc:91:5: note:   no known conversion for argument 1 from ‘std::ostream {aka std::basic_ostream<char>}’ to ‘short int’
In file included from /usr/include/c++/6.2.1/iostream:39:0,
                 from ../include/crucible/chatter.h:5,
                 from chatter.cc:1:
/usr/include/c++/6.2.1/ostream:181:7: note: candidate: std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(short unsigned int) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]
       operator<<(unsigned short __n)
       ^~~~~~~~
/usr/include/c++/6.2.1/ostream:181:7: note:   no known conversion for argument 1 from ‘std::ostream {aka std::basic_ostream<char>}’ to ‘short unsigned int’
In file included from /usr/include/c++/6.2.1/ostream:638:0,
                 from /usr/include/c++/6.2.1/iostream:39,
                 from ../include/crucible/chatter.h:5,
                 from chatter.cc:1:
/usr/include/c++/6.2.1/bits/ostream.tcc:105:5: note: candidate: std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(int) [with _CharT = char; _Traits = std::char_traits<char>]
     basic_ostream<_CharT, _Traits>::
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/6.2.1/bits/ostream.tcc:105:5: note:   no known conversion for argument 1 from ‘std::ostream {aka std::basic_ostream<char>}’ to ‘int’
In file included from /usr/include/c++/6.2.1/iostream:39:0,
                 from ../include/crucible/chatter.h:5,
                 from chatter.cc:1:
/usr/include/c++/6.2.1/ostream:192:7: note: candidate: std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(unsigned int) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]
       operator<<(unsigned int __n)
       ^~~~~~~~
/usr/include/c++/6.2.1/ostream:192:7: note:   no known conversion for argument 1 from ‘std::ostream {aka std::basic_ostream<char>}’ to ‘unsigned int’
/usr/include/c++/6.2.1/ostream:201:7: note: candidate: std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(long long int) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]
       operator<<(long long __n)
       ^~~~~~~~
/usr/include/c++/6.2.1/ostream:201:7: note:   no known conversion for argument 1 from ‘std::ostream {aka std::basic_ostream<char>}’ to ‘long long int’
/usr/include/c++/6.2.1/ostream:205:7: note: candidate: std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(long long unsigned int) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]
       operator<<(unsigned long long __n)
       ^~~~~~~~
/usr/include/c++/6.2.1/ostream:205:7: note:   no known conversion for argument 1 from ‘std::ostream {aka std::basic_ostream<char>}’ to ‘long long unsigned int’
/usr/include/c++/6.2.1/ostream:220:7: note: candidate: std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(double) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]
       operator<<(double __f)
       ^~~~~~~~
/usr/include/c++/6.2.1/ostream:220:7: note:   no known conversion for argument 1 from ‘std::ostream {aka std::basic_ostream<char>}’ to ‘double’
/usr/include/c++/6.2.1/ostream:224:7: note: candidate: std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(float) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]
       operator<<(float __f)
       ^~~~~~~~
/usr/include/c++/6.2.1/ostream:224:7: note:   no known conversion for argument 1 from ‘std::ostream {aka std::basic_ostream<char>}’ to ‘float’
/usr/include/c++/6.2.1/ostream:232:7: note: candidate: std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(long double) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]
       operator<<(long double __f)
       ^~~~~~~~
/usr/include/c++/6.2.1/ostream:232:7: note:   no known conversion for argument 1 from ‘std::ostream {aka std::basic_ostream<char>}’ to ‘long double’
/usr/include/c++/6.2.1/ostream:245:7: note: candidate: std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(const void*) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]
       operator<<(const void* __p)
       ^~~~~~~~
/usr/include/c++/6.2.1/ostream:245:7: note:   no known conversion for argument 1 from ‘std::ostream {aka std::basic_ostream<char>}’ to ‘const void*’
In file included from /usr/include/c++/6.2.1/ostream:638:0,
                 from /usr/include/c++/6.2.1/iostream:39,
                 from ../include/crucible/chatter.h:5,
                 from chatter.cc:1:
/usr/include/c++/6.2.1/bits/ostream.tcc:119:5: note: candidate: std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator<<(std::basic_ostream<_CharT, _Traits>::__streambuf_type*) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__streambuf_type = std::basic_streambuf<char>]
     basic_ostream<_CharT, _Traits>::
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/6.2.1/bits/ostream.tcc:119:5: note:   no known conversion for argument 1 from ‘std::ostream {aka std::basic_ostream<char>}’ to ‘std::basic_ostream<char>::__streambuf_type* {aka std::basic_streambuf<char>*}’
In file included from /usr/include/c++/6.2.1/string:52:0,
                 from /usr/include/c++/6.2.1/stdexcept:39,
                 from /usr/include/c++/6.2.1/array:39,
                 from /usr/include/c++/6.2.1/tuple:39,
                 from /usr/include/c++/6.2.1/functional:55,
                 from ../include/crucible/chatter.h:4,
                 from chatter.cc:1:
/usr/include/c++/6.2.1/bits/basic_string.h:5325:5: note: candidate: template<class _CharT, class _Traits, class _Alloc> std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&)
     operator<<(basic_ostream<_CharT, _Traits>& __os,
     ^~~~~~~~
/usr/include/c++/6.2.1/bits/basic_string.h:5325:5: note:   template argument deduction/substitution failed:
In file included from chatter.cc:1:0:
../include/crucible/chatter.h:94:18: note:   ‘std::ostream {aka std::basic_ostream<char>}’ is not derived from ‘const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>’
    c.get_os() << arg;
                  ^~~
In file included from /usr/include/c++/6.2.1/bits/ios_base.h:46:0,
                 from /usr/include/c++/6.2.1/ios:42,
                 from /usr/include/c++/6.2.1/ostream:38,
                 from /usr/include/c++/6.2.1/iostream:39,
                 from ../include/crucible/chatter.h:5,
                 from chatter.cc:1:
/usr/include/c++/6.2.1/system_error:209:5: note: candidate: template<class _CharT, class _Traits> std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, const std::error_code&)
     operator<<(basic_ostream<_CharT, _Traits>& __os, const error_code& __e)
     ^~~~~~~~
/usr/include/c++/6.2.1/system_error:209:5: note:   template argument deduction/substitution failed:
In file included from chatter.cc:1:0:
../include/crucible/chatter.h:94:18: note:   cannot convert ‘arg’ (type ‘std::ostream {aka std::basic_ostream<char>}’) to type ‘const std::error_code&’
    c.get_os() << arg;
                  ^~~
In file included from /usr/include/c++/6.2.1/iostream:39:0,
                 from ../include/crucible/chatter.h:5,
                 from chatter.cc:1:
/usr/include/c++/6.2.1/ostream:497:5: note: candidate: template<class _CharT, class _Traits> std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, _CharT)
     operator<<(basic_ostream<_CharT, _Traits>& __out, _CharT __c)
     ^~~~~~~~
/usr/include/c++/6.2.1/ostream:497:5: note:   template argument deduction/substitution failed:
In file included from chatter.cc:1:0:
../include/crucible/chatter.h:94:18: note:   deduced conflicting types for parameter ‘_CharT’ (‘char’ and ‘std::basic_ostream<char>’)
    c.get_os() << arg;
                  ^~~
In file included from /usr/include/c++/6.2.1/iostream:39:0,
                 from ../include/crucible/chatter.h:5,
                 from chatter.cc:1:
/usr/include/c++/6.2.1/ostream:502:5: note: candidate: template<class _CharT, class _Traits> std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, char)
     operator<<(basic_ostream<_CharT, _Traits>& __out, char __c)
     ^~~~~~~~
/usr/include/c++/6.2.1/ostream:502:5: note:   template argument deduction/substitution failed:
In file included from chatter.cc:1:0:
../include/crucible/chatter.h:94:18: note:   cannot convert ‘arg’ (type ‘std::ostream {aka std::basic_ostream<char>}’) to type ‘char’
    c.get_os() << arg;
                  ^~~
In file included from /usr/include/c++/6.2.1/iostream:39:0,
                 from ../include/crucible/chatter.h:5,
                 from chatter.cc:1:
/usr/include/c++/6.2.1/ostream:508:5: note: candidate: template<class _Traits> std::basic_ostream<char, _Traits>& std::operator<<(std::basic_ostream<char, _Traits>&, char)
     operator<<(basic_ostream<char, _Traits>& __out, char __c)
     ^~~~~~~~
/usr/include/c++/6.2.1/ostream:508:5: note:   template argument deduction/substitution failed:
In file included from chatter.cc:1:0:
../include/crucible/chatter.h:94:18: note:   cannot convert ‘arg’ (type ‘std::ostream {aka std::basic_ostream<char>}’) to type ‘char’
    c.get_os() << arg;
                  ^~~
In file included from /usr/include/c++/6.2.1/iostream:39:0,
                 from ../include/crucible/chatter.h:5,
                 from chatter.cc:1:
/usr/include/c++/6.2.1/ostream:514:5: note: candidate: template<class _Traits> std::basic_ostream<char, _Traits>& std::operator<<(std::basic_ostream<char, _Traits>&, signed char)
     operator<<(basic_ostream<char, _Traits>& __out, signed char __c)
     ^~~~~~~~
/usr/include/c++/6.2.1/ostream:514:5: note:   template argument deduction/substitution failed:
In file included from chatter.cc:1:0:
../include/crucible/chatter.h:94:18: note:   cannot convert ‘arg’ (type ‘std::ostream {aka std::basic_ostream<char>}’) to type ‘signed char’
    c.get_os() << arg;
                  ^~~
In file included from /usr/include/c++/6.2.1/iostream:39:0,
                 from ../include/crucible/chatter.h:5,
                 from chatter.cc:1:
/usr/include/c++/6.2.1/ostream:519:5: note: candidate: template<class _Traits> std::basic_ostream<char, _Traits>& std::operator<<(std::basic_ostream<char, _Traits>&, unsigned char)
     operator<<(basic_ostream<char, _Traits>& __out, unsigned char __c)
     ^~~~~~~~
/usr/include/c++/6.2.1/ostream:519:5: note:   template argument deduction/substitution failed:
In file included from chatter.cc:1:0:
../include/crucible/chatter.h:94:18: note:   cannot convert ‘arg’ (type ‘std::ostream {aka std::basic_ostream<char>}’) to type ‘unsigned char’
    c.get_os() << arg;
                  ^~~
In file included from /usr/include/c++/6.2.1/iostream:39:0,
                 from ../include/crucible/chatter.h:5,
                 from chatter.cc:1:
/usr/include/c++/6.2.1/ostream:539:5: note: candidate: template<class _CharT, class _Traits> std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, const _CharT*)
     operator<<(basic_ostream<_CharT, _Traits>& __out, const _CharT* __s)
     ^~~~~~~~
/usr/include/c++/6.2.1/ostream:539:5: note:   template argument deduction/substitution failed:
In file included from chatter.cc:1:0:
../include/crucible/chatter.h:94:18: note:   mismatched types ‘const _CharT*’ and ‘std::basic_ostream<char>’
    c.get_os() << arg;
                  ^~~
In file included from /usr/include/c++/6.2.1/ostream:638:0,
                 from /usr/include/c++/6.2.1/iostream:39,
                 from ../include/crucible/chatter.h:5,
                 from chatter.cc:1:
/usr/include/c++/6.2.1/bits/ostream.tcc:321:5: note: candidate: template<class _CharT, class _Traits> std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, const char*)
     operator<<(basic_ostream<_CharT, _Traits>& __out, const char* __s)
     ^~~~~~~~
/usr/include/c++/6.2.1/bits/ostream.tcc:321:5: note:   template argument deduction/substitution failed:
In file included from chatter.cc:1:0:
../include/crucible/chatter.h:94:18: note:   cannot convert ‘arg’ (type ‘std::ostream {aka std::basic_ostream<char>}’) to type ‘const char*’
    c.get_os() << arg;
                  ^~~
In file included from /usr/include/c++/6.2.1/iostream:39:0,
                 from ../include/crucible/chatter.h:5,
                 from chatter.cc:1:
/usr/include/c++/6.2.1/ostream:556:5: note: candidate: template<class _Traits> std::basic_ostream<char, _Traits>& std::operator<<(std::basic_ostream<char, _Traits>&, const char*)
     operator<<(basic_ostream<char, _Traits>& __out, const char* __s)
     ^~~~~~~~
/usr/include/c++/6.2.1/ostream:556:5: note:   template argument deduction/substitution failed:
In file included from chatter.cc:1:0:
../include/crucible/chatter.h:94:18: note:   cannot convert ‘arg’ (type ‘std::ostream {aka std::basic_ostream<char>}’) to type ‘const char*’
    c.get_os() << arg;
                  ^~~
In file included from /usr/include/c++/6.2.1/iostream:39:0,
                 from ../include/crucible/chatter.h:5,
                 from chatter.cc:1:
/usr/include/c++/6.2.1/ostream:569:5: note: candidate: template<class _Traits> std::basic_ostream<char, _Traits>& std::operator<<(std::basic_ostream<char, _Traits>&, const signed char*)
     operator<<(basic_ostream<char, _Traits>& __out, const signed char* __s)
     ^~~~~~~~
/usr/include/c++/6.2.1/ostream:569:5: note:   template argument deduction/substitution failed:
In file included from chatter.cc:1:0:
../include/crucible/chatter.h:94:18: note:   cannot convert ‘arg’ (type ‘std::ostream {aka std::basic_ostream<char>}’) to type ‘const signed char*’
    c.get_os() << arg;
                  ^~~
In file included from /usr/include/c++/6.2.1/iostream:39:0,
                 from ../include/crucible/chatter.h:5,
                 from chatter.cc:1:
/usr/include/c++/6.2.1/ostream:574:5: note: candidate: template<class _Traits> std::basic_ostream<char, _Traits>& std::operator<<(std::basic_ostream<char, _Traits>&, const unsigned char*)
     operator<<(basic_ostream<char, _Traits>& __out, const unsigned char* __s)
     ^~~~~~~~
/usr/include/c++/6.2.1/ostream:574:5: note:   template argument deduction/substitution failed:
In file included from chatter.cc:1:0:
../include/crucible/chatter.h:94:18: note:   cannot convert ‘arg’ (type ‘std::ostream {aka std::basic_ostream<char>}’) to type ‘const unsigned char*’
    c.get_os() << arg;
                  ^~~
In file included from /usr/include/c++/6.2.1/iostream:39:0,
                 from ../include/crucible/chatter.h:5,
                 from chatter.cc:1:
/usr/include/c++/6.2.1/ostream:628:5: note: candidate: std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&&, const _Tp&) [with _CharT = char; _Traits = std::char_traits<char>; _Tp = std::basic_ostream<char>] <near match>
     operator<<(basic_ostream<_CharT, _Traits>&& __os, const _Tp& __x)
     ^~~~~~~~
/usr/include/c++/6.2.1/ostream:628:5: note:   conversion of argument 1 would be ill-formed:
In file included from chatter.cc:1:0:
../include/crucible/chatter.h:94:12: error: cannot bind ‘std::ostream {aka std::basic_ostream<char>}’ lvalue to ‘std::basic_ostream<char>&&’
    c.get_os() << arg;
    ~~~~~~~~^~
chatter.cc: At global scope:
chatter.cc:18:9: error: ‘template<class> class std::auto_ptr’ is deprecated [-Werror=deprecated-declarations]
  static auto_ptr<set<string>> chatter_names;
         ^~~~~~~~
In file included from /usr/include/c++/6.2.1/memory:81:0,
                 from ../include/crucible/resource.h:8,
                 from ../include/crucible/process.h:4,
                 from chatter.cc:4:
/usr/include/c++/6.2.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
cc1plus: all warnings being treated as errors
make[1]: *** [Makefile:34: chatter.o] Error 1
make[1]: Leaving directory '/home/nefelim4ag/Insync/Documents/Dump/Coding/bees/lib'
make: *** [Makefile:9: lib] Error 2
```

Host Arch x64 
g++ (GCC) 6.2.1 20160830
GNU Make 4.2.1

Thanks.

**Comment by uroni** [comment]
Doesn't compile on Debian Jessie with GCC 5.3.1 either. Same errors.

**Comment by Zygo** [comment]
I upgraded my ancient toolchain and fixed some old broken things.  I tested on Debian GCC 6.2.0.  It builds and the first hour of runtime looks OK.

Thanks for the report.  Please let me know if I missed anything.

**Comment by Nefelim4ag** [comment]
Thanks, fixed
